/**
 * Montatorul modern shell injected into elcats embed pages.
 * Hides legacy layout, rebuilds scheme + parts/nav with search.
 */

export function buildElcatsUiCss(): string {
  return [
    '<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, viewport-fit=cover" />',
    '<style id="montatorul-elcats-skin">',
    ":root,html.mont-light{",
    "--m-bg:#f8f7f4;--m-fg:#1a1a1a;--m-card:#ffffff;--m-muted:#e8e6e1;",
    "--m-muted-fg:#666;--m-border:#d1cec7;--m-primary:#ff6b00;",
    "--m-primary-fg:#fff;--m-primary-soft:rgba(255,107,0,.12);",
    "--m-link:#c2410c;--m-danger:#dc2626;--m-ok:#16a34a;",
    "--m-scheme:#f0eeea;--m-shadow:0 1px 3px rgba(0,0,0,.08);",
    "--m-radius:12px;--m-font:system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif",
    "}",
    "html.mont-dark{",
    "--m-bg:#121212;--m-fg:#f0f0f0;--m-card:#1e1e1e;--m-muted:#2a2a2a;",
    "--m-muted-fg:#a8a8a8;--m-border:#333;--m-primary:#ff8533;",
    "--m-primary-fg:#121212;--m-primary-soft:rgba(255,133,51,.16);",
    "--m-link:#ffb070;--m-danger:#f87171;--m-ok:#4ade80;",
    "--m-scheme:#1a1a1a;--m-shadow:0 1px 3px rgba(0,0,0,.35)",
    "}",
    "*,*::before,*::after{box-sizing:border-box}",
    "html,body{margin:0!important;padding:0!important;min-width:0!important;width:100%!important;",
    "max-width:100%!important;background:var(--m-bg)!important;color:var(--m-fg)!important;",
    "font-family:var(--m-font)!important;line-height:1.45!important;-webkit-text-size-adjust:100%}",
    "body,form,#all_document,#content,#aspnetForm{min-width:0!important;max-width:100%!important}",
    "/* hide legacy chrome */",
    "#head,#footer,.bg-login,.form-login,#background,iframe[src*=googlesyndication],",
    "ins.adsbygoogle,iframe[src*=pagead],a[href*='exist.ru'],a[href*='liveinternet'],",
    "img[src*='pagead'],.banner_texinfo,#techwork,#mont-source{display:none!important}",
    "#content{background:transparent!important;padding:0!important;min-height:0!important}",
    "#all_document{padding:0!important;margin:0!important}",
    "/* ---- app shell: fill iframe, list scrolls, scheme sticky ---- */",
    "html,body{height:100%!important;overflow:hidden!important}",
    "#all_document,#content,#aspnetForm{height:100%!important;min-height:100%!important;",
    "display:flex!important;flex-direction:column!important;overflow:hidden!important;flex:1!important}",
    "#mont-app{display:flex;flex-direction:column;flex:1 1 auto;height:100%;min-height:0;",
    "max-height:100%;overflow:hidden;background:var(--m-bg);color:var(--m-fg)}",
    ".mont-top{flex-shrink:0;z-index:50;background:var(--m-card);border-bottom:1px solid var(--m-border);",
    "box-shadow:var(--m-shadow);padding:10px 12px;display:flex;flex-direction:column;gap:8px}",
    ".mont-top-row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}",
    ".mont-crumbs{font-size:12px;color:var(--m-muted-fg);line-height:1.35;word-break:break-word;",
    "overflow-wrap:anywhere;max-width:100%}",
    ".mont-crumbs a{color:var(--m-link);text-decoration:none;font-weight:500}",
    ".mont-crumbs a:hover{color:var(--m-primary);text-decoration:underline}",
    ".mont-crumbs .mont-here{color:var(--m-fg);font-weight:600}",
    ".mont-search-wrap{flex:1;min-width:min(100%,220px);position:relative}",
    ".mont-search{width:100%;height:42px;border-radius:10px;border:1px solid var(--m-border);",
    "background:var(--m-bg);color:var(--m-fg);padding:0 12px 0 38px;font-size:15px;outline:none}",
    ".mont-search:focus{border-color:var(--m-primary);box-shadow:0 0 0 3px var(--m-primary-soft)}",
    ".mont-search-ico{position:absolute;left:12px;top:50%;transform:translateY(-50%);color:var(--m-muted-fg);pointer-events:none;font-size:14px}",
    ".mont-meta{font-size:11px;color:var(--m-muted-fg);white-space:nowrap}",
    ".mont-badge{display:inline-flex;align-items:center;height:24px;padding:0 8px;border-radius:999px;",
    "background:var(--m-primary-soft);color:var(--m-primary);font-size:11px;font-weight:700}",
    ".mont-body{display:flex;flex:1;min-height:0;overflow:hidden;align-items:stretch}",
    /* scheme column stays put while list scrolls */
    ".mont-scheme-col{flex:1.1;min-width:0;max-width:58%;display:flex;flex-direction:column;",
    "border-right:1px solid var(--m-border);background:var(--m-scheme);min-height:0;overflow:hidden}",
    ".mont-scheme-toolbar{display:flex;gap:6px;align-items:center;padding:8px 10px;border-bottom:1px solid var(--m-border);",
    "background:var(--m-card);flex-wrap:wrap;flex-shrink:0}",
    ".mont-scheme-toolbar span{font-size:12px;font-weight:600;color:var(--m-fg);margin-right:auto}",
    ".mont-scheme-tabs{display:flex;gap:4px;flex-wrap:wrap;padding:6px 10px;border-bottom:1px solid var(--m-border);",
    "background:var(--m-card);flex-shrink:0}",
    ".mont-scheme-tab{height:30px;padding:0 10px;border-radius:8px;border:1px solid var(--m-border);",
    "background:var(--m-bg);color:var(--m-fg);cursor:pointer;font-size:12px;font-weight:600}",
    ".mont-scheme-tab.is-on{background:var(--m-primary);color:var(--m-primary-fg);border-color:var(--m-primary)}",
    ".mont-icon-btn{height:34px;min-width:34px;padding:0 10px;border-radius:8px;border:1px solid var(--m-border);",
    "background:var(--m-card);color:var(--m-fg);cursor:pointer;font-weight:700;font-size:14px}",
    ".mont-icon-btn:hover{border-color:var(--m-primary);color:var(--m-primary)}",
    ".mont-scheme-view{flex:1;overflow:auto;-webkit-overflow-scrolling:touch;position:relative;",
    "min-height:0;cursor:grab;background:var(--m-scheme)}",
    ".mont-scheme-view.is-panning{cursor:grabbing}",
    ".mont-scheme-stage{position:relative;transform-origin:0 0;width:max-content;margin:0 auto}",
    ".mont-scheme-stage img.mont-scheme-img{display:block;max-width:none!important;height:auto!important;",
    "border:1px solid var(--m-border);background:#fff;user-select:none;-webkit-user-drag:none}",
    "html.mont-dark .mont-scheme-stage img.mont-scheme-img{background:#111}",
    ".mont-hotspot{position:absolute;border:2px solid var(--m-primary);border-radius:4px;",
    "background:rgba(255,107,0,.28);color:var(--m-fg);font-size:11px;font-weight:800;",
    "display:flex;align-items:center;justify-content:center;cursor:pointer;z-index:2;",
    "box-shadow:0 1px 3px rgba(0,0,0,.2);min-width:22px;min-height:22px;padding:0 3px}",
    ".mont-hotspot.is-off{opacity:.3;border-style:dashed;background:transparent}",
    ".mont-hotspot.is-active,.mont-hotspot:hover{background:var(--m-primary);color:var(--m-primary-fg);z-index:3;",
    "opacity:1}",
    ".mont-list-col{flex:1 1 42%;min-width:280px;max-width:520px;display:flex;flex-direction:column;",
    "background:var(--m-bg);min-height:200px;overflow:hidden}",
    ".mont-list-head{padding:10px 12px;border-bottom:1px solid var(--m-border);background:var(--m-card);",
    "display:flex;align-items:center;gap:8px;justify-content:space-between;flex-shrink:0;flex-wrap:wrap}",
    ".mont-list-head h2{margin:0;font-size:14px;font-weight:700}",
    ".mont-list{flex:1 1 auto;overflow-y:auto;overflow-x:hidden;-webkit-overflow-scrolling:touch;",
    "padding:10px;display:flex;flex-direction:column;gap:10px;min-height:120px}",
    ".mont-card{background:var(--m-card);border:1px solid var(--m-border);border-radius:14px;",
    "padding:0;box-shadow:var(--m-shadow);cursor:default;transition:border-color .12s,box-shadow .12s;",
    "overflow:visible;min-width:0;flex-shrink:0}",
    ".mont-card.is-active{border-color:var(--m-primary);box-shadow:0 0 0 2px var(--m-primary-soft)}",
    ".mont-card.is-hidden{display:none!important}",
    ".mont-card-head{display:flex;gap:10px;align-items:center;padding:12px;cursor:pointer;",
    "border-bottom:1px solid var(--m-border);min-height:48px}",
    ".mont-card-head:hover{background:var(--m-primary-soft)}",
    ".mont-callout{flex-shrink:0;min-width:40px;height:32px;padding:0 8px;border-radius:10px;",
    "background:var(--m-primary);color:var(--m-primary-fg);font-weight:800;font-size:13px;",
    "display:inline-flex;align-items:center;justify-content:center}",
    ".mont-card-title{font-size:13.5px;font-weight:700;color:var(--m-fg);line-height:1.35;",
    "overflow-wrap:anywhere;word-break:break-word;flex:1;min-width:0}",
    ".mont-card-count{flex-shrink:0;font-size:11px;color:var(--m-muted-fg);font-weight:600;",
    "background:var(--m-muted);padding:3px 8px;border-radius:999px}",
    ".mont-variants{display:flex;flex-direction:column;gap:0;min-height:0}",
    ".mont-var{padding:10px 12px;border-top:1px solid var(--m-border);background:var(--m-bg);",
    "min-height:44px}",
    ".mont-var:first-child{border-top:0}",
    ".mont-var-desc{font-size:12px;color:var(--m-muted-fg);line-height:1.45;margin:0 0 8px;",
    "overflow-wrap:anywhere;word-break:break-word;white-space:normal}",
    ".mont-var-desc b{color:var(--m-fg);font-weight:600}",
    ".mont-card-meta{display:flex;flex-wrap:wrap;gap:5px;margin-bottom:8px;align-items:center}",
    ".mont-chip{font-size:10.5px;padding:2px 7px;border-radius:999px;background:var(--m-muted);color:var(--m-muted-fg);",
    "max-width:100%;overflow-wrap:anywhere;word-break:break-word;line-height:1.3}",
    ".mont-chip.qty{background:var(--m-primary-soft);color:var(--m-primary);font-weight:700}",
    ".mont-oem{display:inline-flex;align-items:center;gap:4px;border:1.5px solid var(--m-primary);",
    "background:var(--m-primary-soft);color:var(--m-primary);border-radius:8px;padding:6px 10px;",
    "font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;font-weight:700;",
    "cursor:pointer;min-height:32px;line-height:1.2;max-width:100%;overflow-wrap:anywhere}",
    ".mont-oem:hover{background:var(--m-primary);color:var(--m-primary-fg)}",
    ".mont-oem.is-loading{border-style:dashed;color:var(--m-muted-fg);background:var(--m-muted);border-color:var(--m-border);cursor:wait}",
    ".mont-oem.is-fail{border-color:var(--m-danger);color:var(--m-danger);background:rgba(220,38,38,.08);cursor:pointer}",
    ".mont-oem.is-repl{border-color:var(--m-ok);color:var(--m-ok);background:rgba(22,163,74,.1)}",
    ".mont-oem.is-md{border-style:solid;font-family:var(--m-font);font-size:11px;letter-spacing:0}",
    ".mont-oem-row{display:flex;flex-wrap:wrap;gap:6px;align-items:center}",
    ".mont-oem-label{font-size:10px;text-transform:uppercase;letter-spacing:.04em;color:var(--m-muted-fg);font-weight:600}",
    ".mont-empty{padding:28px 16px;text-align:center;color:var(--m-muted-fg);font-size:13px}",
    ".mont-nav-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:10px;padding:12px;",
    "overflow:auto;flex:1;min-height:0;align-content:start}",
    ".mont-nav-grid.is-schemes{grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:14px}",
    ".mont-nav-item{display:flex;align-items:flex-start;gap:10px;padding:12px 14px;background:var(--m-card);",
    "border:1px solid var(--m-border);border-radius:var(--m-radius);cursor:pointer;text-align:left;",
    "color:var(--m-fg);font-size:13px;font-weight:600;box-shadow:var(--m-shadow);min-height:48px;",
    "min-width:0;overflow:hidden}",
    ".mont-nav-item:hover{border-color:var(--m-primary);background:var(--m-primary-soft)}",
    ".mont-nav-item.is-hidden{display:none!important}",
    ".mont-nav-item.is-scheme{flex-direction:column;align-items:stretch;padding:10px;gap:8px}",
    ".mont-nav-item.is-scheme:hover{background:var(--m-card);box-shadow:0 0 0 2px var(--m-primary-soft)}",
    ".mont-scheme-thumb{width:100%;aspect-ratio:4/3;object-fit:contain;background:var(--m-scheme);",
    "border:1px solid var(--m-border);border-radius:10px;display:block}",
    ".mont-nav-item .arrow{color:var(--m-primary);font-size:18px;font-weight:700;flex-shrink:0;line-height:1.2}",
    ".mont-nav-item .mont-nav-label{flex:1;min-width:0;overflow-wrap:anywhere;word-break:break-word;line-height:1.35}",
    ".mont-scheme-hint{padding:10px 14px;margin:0 12px;font-size:12.5px;color:var(--m-muted-fg);",
    "background:var(--m-primary-soft);border:1px solid var(--m-primary);border-radius:10px}",
    ".mont-scheme-hint strong{color:var(--m-primary)}",
    ".mont-toast{position:fixed;bottom:16px;left:50%;transform:translateX(-50%);background:var(--m-primary);",
    "color:#fff;padding:10px 16px;border-radius:12px;font-size:13px;font-weight:600;z-index:99999;",
    "box-shadow:0 8px 24px rgba(255,107,0,.35);display:none;max-width:92%;text-align:center}",
    ".mont-ocr-bar{font-size:11px;color:var(--m-muted-fg);padding:0 2px}",
    "@media (max-width:900px){",
    "  html,body,#all_document,#content{overflow:auto!important;height:auto!important}",
    "  #mont-app{height:auto;max-height:none;overflow:visible}",
    "  .mont-body{flex-direction:column;overflow:visible}",
    "  .mont-scheme-col{border-right:0;border-bottom:1px solid var(--m-border);flex:none;",
    "    max-width:100%;max-height:min(42vh,380px);position:sticky;top:0;z-index:20}",
    "  .mont-list-col{max-width:none;flex:1;min-height:40vh;overflow:visible}",
    "  .mont-list{overflow:visible}",
    "  .mont-scheme-view{min-height:200px}",
    "}",
    "@media (max-width:480px){",
    "  .mont-search{font-size:16px}",
    "  .mont-nav-grid{grid-template-columns:1fr}",
    "}",
    "</style>",
  ].join("\n");
}

/** Injected bridge + modern UI. page/origin/dir already JSON.stringify'd. */
export function buildElcatsUiScript(
  pageJson: string,
  originJson: string,
  dirJson: string
): string {
  // Built as one function body string — no ${} template holes inside inject.
  const lines = [
    '<script id="montatorul-elcats-bridge">',
    "(function () {",
    "  var PAGE = " + pageJson + ";",
    "  var ELCATS = " + originJson + ";",
    "  var PAGEDIR = " + dirJson + ";",
    "  var APP = window.location.origin;",
    '  var PROXY = APP + "/api/parts/elcats-embed?url=";',
    '  var CODE_API = APP + "/api/parts/elcats-code";',
    "  var schemeZoom = 1;",
    "  var ocrCache = {};", // only successful OEMs
    "  var ocrInflight = {};",
    "  var ocrQueue = [];",
    "  var ocrActive = 0;",
    "  var OCR_CONCURRENCY = 2;",
    "  var ocrDone = 0;",
    "  var ocrTotal = 0;",
    "  var state = { mode: 'other', parts: [], nav: [], crumbs: [], query: '', activeCallout: '', schemes: [], schemeIdx: 0 };",

    "  function applyTheme() {",
    "    var dark = false;",
    "    try {",
    "      dark = !!(parent && parent.document && parent.document.documentElement &&",
    "        parent.document.documentElement.classList.contains('dark'));",
    "    } catch (e) {",
    "      try { dark = window.matchMedia('(prefers-color-scheme: dark)').matches; } catch (e2) {}",
    "    }",
    "    document.documentElement.classList.toggle('mont-dark', dark);",
    "    document.documentElement.classList.toggle('mont-light', !dark);",
    "  }",
    "  applyTheme();",
    "  try {",
    "    if (parent && parent.document && parent.document.documentElement) {",
    "      new MutationObserver(applyTheme).observe(parent.document.documentElement, { attributes: true, attributeFilter: ['class'] });",
    "    }",
    "  } catch (e) {}",

    "  function stripBases() {",
    "    try {",
    "      var bases = document.getElementsByTagName('base');",
    "      for (var i = bases.length - 1; i >= 0; i--) bases[i].parentNode.removeChild(bases[i]);",
    "    } catch (e) {}",
    "  }",
    "  stripBases();",
    "  try { new MutationObserver(stripBases).observe(document.documentElement, { childList: true, subtree: true }); } catch (e) {}",

    "  // Map wrongly-resolved local assets → elcats (jquery injects ../CImages/load.gif etc.)",
    "  function fixElcatsAssetUrl(u) {",
    "    if (!u) return u;",
    "    var s = String(u);",
    "    try {",
    "      // already elcats",
    "      if (/^https?:\\/\\/(www\\.)?elcats\\.ru\\//i.test(s)) return s;",
    "      // protocol-relative //pagead... leave",
    "      if (s.indexOf('//') === 0 && s.indexOf('elcats') < 0 && s.indexOf(APP) < 0) return s;",
    "      var origin = window.location.origin;",
    "      if (s.indexOf(origin) === 0) {",
    "        var path = s.slice(origin.length);",
    "        // /api/CImages/... or /js/... /WebResource... /CImages...",
    "        path = path.replace(/^\\/api(?=\\/CImages|\\/Images|\\/js|\\/style|\\/img|\\/WebResource)/i, '');",
    "        if (/^\\/(js|style|img|CImages|Images|WebResource|ScriptResource|CImage)/i.test(path) ||",
    "            /\\/(Codes|CImage)\\.ashx/i.test(path)) {",
    "          return 'https://www.elcats.ru' + path;",
    "        }",
    "      }",
    "      // root-relative assets",
    "      if (s.charAt(0) === '/' && !s.startsWith('/api/parts/elcats-embed')) {",
    "        if (/^\\/(js|style|img|CImages|Images|WebResource|ScriptResource)/i.test(s) ||",
    "            /\\/(Codes|CImage)\\.ashx/i.test(s)) {",
    "          return 'https://www.elcats.ru' + s;",
    "        }",
    "      }",
    "      // relative ../CImages/load.gif — resolve against elcats PAGE dir",
    "      if (!/^https?:\\/\\//i.test(s) && /CImages|Images\\/|load\\.gif|WebResource|\\.axd|\\.ashx|\\/js\\//i.test(s)) {",
    "        return new URL(s, PAGE).toString();",
    "      }",
    "    } catch (e) {}",
    "    return s;",
    "  }",
    "  function patchAssetElement(el) {",
    "    if (!el || !el.getAttribute) return;",
    "    var attrs = ['src', 'href'];",
    "    for (var i = 0; i < attrs.length; i++) {",
    "      var a = attrs[i];",
    "      var raw = el.getAttribute(a);",
    "      if (!raw) continue;",
    "      var fixed = fixElcatsAssetUrl(raw);",
    "      if (fixed && fixed !== raw) {",
    "        try { el.setAttribute(a, fixed); } catch (e) {}",
    "      }",
    "    }",
    "  }",
    "  // Hard-patch Image.src so jQuery-injected ../CImages/load.gif never hits /api/CImages",
    "  try {",
    "    var imgDesc = Object.getOwnPropertyDescriptor(HTMLImageElement.prototype, 'src');",
    "    if (imgDesc && imgDesc.set) {",
    "      Object.defineProperty(HTMLImageElement.prototype, 'src', {",
    "        configurable: true,",
    "        enumerable: true,",
    "        get: function () { return imgDesc.get.call(this); },",
    "        set: function (v) {",
    "          return imgDesc.set.call(this, fixElcatsAssetUrl(v));",
    "        }",
    "      });",
    "    }",
    "  } catch (e) {}",
    "  document.addEventListener('error', function (ev) {",
    "    var t = ev.target;",
    "    if (!t || !t.tagName) return;",
    "    var tag = t.tagName.toUpperCase();",
    "    if (tag !== 'IMG' && tag !== 'SCRIPT' && tag !== 'LINK') return;",
    "    if (t.getAttribute('data-mont-asset-fix')) return;",
    "    var attr = tag === 'LINK' ? 'href' : 'src';",
    "    var cur = t.getAttribute(attr) || '';",
    "    try { if (!cur && t[attr]) cur = t[attr]; } catch (e) {}",
    "    var fixed = fixElcatsAssetUrl(cur);",
    "    if (fixed && fixed !== cur && /elcats\\.ru/i.test(fixed)) {",
    "      t.setAttribute('data-mont-asset-fix', '1');",
    "      try { t[attr] = fixed; } catch (e) { t.setAttribute(attr, fixed); }",
    "    }",
    "  }, true);",
    "  try {",
    "    new MutationObserver(function (muts) {",
    "      for (var i = 0; i < muts.length; i++) {",
    "        var nodes = muts[i].addedNodes;",
    "        for (var j = 0; j < nodes.length; j++) {",
    "          var n = nodes[j];",
    "          if (n.nodeType !== 1) continue;",
    "          patchAssetElement(n);",
    "          if (n.querySelectorAll) {",
    "            var list = n.querySelectorAll('img[src],script[src],link[href],img');",
    "            for (var k = 0; k < list.length; k++) patchAssetElement(list[k]);",
    "          }",
    "        }",
    "        if (muts[i].type === 'attributes' && muts[i].target) patchAssetElement(muts[i].target);",
    "      }",
    "    }).observe(document.documentElement, { childList: true, subtree: true, attributes: true, attributeFilter: ['src', 'href'] });",
    "  } catch (e) {}",
    "  try {",
    "    var early = document.querySelectorAll('script[src],link[href],img[src],img');",
    "    for (var ei = 0; ei < early.length; ei++) patchAssetElement(early[ei]);",
    "  } catch (e) {}",

    "  function toast(msg) {",
    "    var el = document.getElementById('montatorul-toast');",
    "    if (!el) { el = document.createElement('div'); el.id = 'montatorul-toast'; el.className = 'mont-toast'; document.body.appendChild(el); }",
    "    el.textContent = msg;",
    "    el.style.display = 'block';",
    "    clearTimeout(el._t);",
    "    el._t = setTimeout(function () { el.style.display = 'none'; }, 2200);",
    "  }",

    // ---- URL / proxy (keep navigation inside our origin) ----
    "  function decodeEntities(s) {",
    "    var t = String(s || '');",
    "    for (var i = 0; i < 3; i++) {",
    "      var n = t.replace(/&amp;/gi, '&').replace(/&quot;/gi, '\"').replace(/&#39;/g, \"'\");",
    "      if (n === t) break;",
    "      t = n;",
    "    }",
    "    return t;",
    "  }",
    "  function absElcats(u) {",
    "    if (!u) return PAGE;",
    "    var s = decodeEntities(String(u).trim());",
    "    if (!s) return PAGE;",
    "    if (/^https?:\\/\\/(www\\.)?elcats\\.ru\\//i.test(s)) return s.replace(/&amp;/gi, '&');",
    "    if (s.indexOf('/api/parts/elcats-embed') >= 0) {",
    "      try {",
    "        var pu = new URL(s, window.location.origin);",
    "        var inner = pu.searchParams.get('url');",
    "        if (inner) return decodeEntities(inner);",
    "      } catch (e) {}",
    "      return PAGE;",
    "    }",
    "    if (/^https?:\\/\\/(www\\.)?elcats\\.ru\\/api\\/parts\\/elcats-embed/i.test(s)) {",
    "      try {",
    "        var bu = new URL(s);",
    "        var inn = bu.searchParams.get('url');",
    "        if (inn) return decodeEntities(inn);",
    "        var baseName = PAGE.split('?')[0].split('/').pop() || 'Group.aspx';",
    "        return new URL(baseName + (bu.search || ''), PAGEDIR).toString();",
    "      } catch (e) { return PAGE; }",
    "    }",
    "    if (/^https?:\\/\\//i.test(s)) {",
    "      try {",
    "        var abs = new URL(s);",
    "        if (/localhost|127\\.0\\.0\\.1/i.test(abs.hostname)) {",
    "          if (abs.pathname.indexOf('/api/parts/elcats-embed') === 0) {",
    "            var inn2 = abs.searchParams.get('url');",
    "            return inn2 ? decodeEntities(inn2) : PAGE;",
    "          }",
    "        }",
    "      } catch (e) {}",
    "    }",
    "    try { return new URL(s, PAGE).toString(); } catch (e) {",
    "      try { return new URL(s, PAGEDIR).toString(); } catch (e2) { return PAGE; }",
    "    }",
    "  }",
    "  function toProxy(u) {",
    "    var s = decodeEntities(String(u || ''));",
    "    if (s.indexOf('/api/parts/elcats-embed?url=') >= 0) {",
    "      try {",
    "        var pu2 = new URL(s, APP);",
    "        var inn3 = pu2.searchParams.get('url');",
    "        if (inn3) return APP + '/api/parts/elcats-embed?url=' + encodeURIComponent(decodeEntities(inn3));",
    "      } catch (e) {}",
    "      if (/^https?:\\/\\//i.test(s)) return s;",
    "      return APP + (s.charAt(0) === '/' ? s : ('/' + s));",
    "    }",
    "    var abs = absElcats(u);",
    "    if (!abs || !/^https?:\\/\\/(www\\.)?elcats\\.ru\\//i.test(abs)) return PROXY + encodeURIComponent(PAGE);",
    "    return PROXY + encodeURIComponent(decodeEntities(abs));",
    "  }",
    "  function goElcats(u) { window.location.href = toProxy(u); }",

    "  function collectFormFields(form, submitter) {",
    "    var out = {};",
    "    try {",
    "      var els = form.elements;",
    "      for (var i = 0; i < els.length; i++) {",
    "        var el = els[i];",
    "        if (!el || !el.name || el.disabled) continue;",
    "        var type = (el.type || '').toLowerCase();",
    "        if (type === 'button' || type === 'reset' || type === 'file' || type === 'submit' || type === 'image') continue;",
    "        if ((type === 'checkbox' || type === 'radio') && !el.checked) continue;",
    "        out[el.name] = el.value;",
    "      }",
    "      if (submitter && submitter.name) out[submitter.name] = submitter.value;",
    "    } catch (e) {}",
    "    return out;",
    "  }",
    "  function resolveFormActionRaw(form) {",
    "    var raw = form.getAttribute('data-mont-action') || form.getAttribute('action') || PAGE;",
    "    raw = String(raw || PAGE);",
    "    if (raw.indexOf('/api/parts/elcats-embed') >= 0) {",
    "      try {",
    "        var pu = new URL(raw, window.location.origin);",
    "        var inn = pu.searchParams.get('url');",
    "        if (inn) return inn;",
    "      } catch (e) {}",
    "      return PAGE;",
    "    }",
    "    return raw;",
    "  }",
    "  function elcatsTargetFromForm(form, submitter) {",
    "    var abs = absElcats(resolveFormActionRaw(form));",
    "    try {",
    "      var u = new URL(abs);",
    "      var fields = collectFormFields(form, submitter);",
    "      for (var k in fields) {",
    "        if (!Object.prototype.hasOwnProperty.call(fields, k) || k === 'url') continue;",
    "        u.searchParams.set(k, fields[k]);",
    "      }",
    "      return u.toString();",
    "    } catch (e) { return abs || PAGE; }",
    "  }",
    "  function navigateFormGet(form, submitter) {",
    "    window.location.href = toProxy(elcatsTargetFromForm(form, submitter));",
    "  }",
    "  function forceFormProxy(form) {",
    "    if (!form) return;",
    "    var method = String(form.getAttribute('method') || form.method || 'get').toLowerCase();",
    "    var target = method === 'post' ? absElcats(resolveFormActionRaw(form)) : elcatsTargetFromForm(form, null);",
    "    var proxied = toProxy(target);",
    "    form.setAttribute('action', proxied);",
    "    try { form.action = proxied; } catch (e) {}",
    "  }",

    // ---- OEM helpers ----
    "  function compactOem(s) { return String(s || '').replace(/\\s+/g, '').toUpperCase().replace(/[^A-Z0-9]/g, ''); }",
    "  function formatOemDisplay(s) {",
    "    var c = compactOem(s);",
    "    var m = c.match(/^(A)(\\d{3})(\\d{3})(\\d{2})(\\d{2})$/i);",
    "    if (m) return m[1] + ' ' + m[2] + ' ' + m[3] + ' ' + m[4] + ' ' + m[5];",
    "    return c;",
    "  }",
    "  function isJunkOem(s) {",
    "    var t = compactOem(s);",
    "    if (t.length < 3 || t.length > 22) return true;",
    "    if (!/\\d/.test(t)) return true;",
    "    // short Kia callouts: 86350, 1327AA — valid",
    "    if (t.length <= 8 && /[A-Z0-9]/.test(t) && !/^NO0/.test(t) && !/0{5,}/.test(t)) return false;",
    "    if (/^NO0{4,}/.test(t)) return true;",
    "    if (/^[A-Z]{1,3}0{6,}$/.test(t)) return true;",
    "    if (/0{5,}/.test(t)) return true;",
    "    var z = (t.match(/0/g) || []).length;",
    "    if (t.length >= 10 && z >= 6 && z / t.length >= 0.5) return true;",
    "    return false;",
    "  }",
    "  function looksLikeOem(s) {",
    "    if (!s) return null;",
    "    var t = String(s).replace(/\\s+/g, ' ').trim();",
    "    var m = t.match(/\\b(A\\s*\\d{3}\\s*\\d{3}\\s*\\d{2}\\s*\\d{2})\\b/i)",
    "      || t.match(/\\b(A\\d{10,12})\\b/i)",
    "      || t.match(/\\b(N9\\d{10,})\\b/i)",
    "      || t.match(/\\b(N\\d{11,14})\\b/i)",
    "      || t.match(/\\b(\\d{5}[\\-][0-9A-Z]{4,10})\\b/i)",
    "      || t.match(/\\b([A-Z]{1,3}\\d{6,})\\b/i);",
    "    if (!m) return null;",
    "    var art = compactOem(m[1]);",
    "    if (isJunkOem(art)) return null;",
    "    return art;",
    "  }",
    "  function postOem(article, name) {",
    "    var art = compactOem(article);",
    "    if (art.length < 5) return;",
    "    if (isJunkOem(art)) {",
    "      toast('Мусорный OEM ' + art + ' (OCR?) — в MD не шлём');",
    "      return;",
    "    }",
    "    try {",
    "      parent.postMessage({ source: 'montatorul-elcats', type: 'oem-search', article: art, name: name || '', page: PAGE }, '*');",
    "      toast('OEM ' + formatOemDisplay(art) + ' → MD');",
    "    } catch (e) {}",
    "  }",
    "  function extractCodeKey(src) {",
    "    if (!src) return null;",
    "    var s = String(src);",
    "    // absolute or relative Codes.ashx?Key=...",
    "    var m = s.match(/Codes\\.ashx\\?Key=([^&\"'#\\s]+)/i) || s.match(/[?&]Key=([^&\"'#\\s]+)/i);",
    "    if (!m) return null;",
    "    var raw = m[1];",
    "    try { return decodeURIComponent(raw.replace(/\\+/g, ' ')); } catch (e) { return raw; }",
    "  }",
    "  function updateOcrBar() {",
    "    var el = document.getElementById('mont-ocr-bar');",
    "    if (!el) return;",
    "    if (!ocrTotal) { el.textContent = ''; return; }",
    "    if (ocrDone >= ocrTotal) el.textContent = 'OEM: ' + ocrDone + '/' + ocrTotal;",
    "    else el.textContent = 'Читаем OEM ' + ocrDone + '/' + ocrTotal + '…';",
    "  }",
    "  function applyOcrToParts(key, art) {",
    "    if (!art) return;",
    "    for (var i = 0; i < state.parts.length; i++) {",
    "      var p = state.parts[i];",
    "      if (p.keys && p.keys.indexOf(key) >= 0) {",
    "        if (!p.oems) p.oems = [];",
    "        if (p.oems.indexOf(art) < 0) p.oems = [art].concat(p.oems.filter(function (x) { return x !== art; }));",
    "      }",
    "      if (p.replaceKeys && p.replaceKeys.indexOf(key) >= 0) {",
    "        if (!p.replaceOems) p.replaceOems = [];",
    "        if (p.replaceOems.indexOf(art) < 0) p.replaceOems.push(art);",
    "      }",
    "      p.search = ((p.callout || '') + ' ' + (p.title || '') + ' ' + (p.desc || '') + ' ' + (p.info || '') + ' ' +",
    "        (p.oems || []).join(' ') + ' ' + (p.replaceOems || []).join(' ')).toLowerCase();",
    "    }",
    "  }",
    "  function resolveCodeKey(key, cb, force) {",
    "    if (!key) { if (cb) cb(null); return; }",
    "    if (!force && ocrCache[key]) { if (cb) cb(ocrCache[key]); return; }",
    "    if (ocrInflight[key]) { if (cb) ocrInflight[key].push(cb); return; }",
    "    ocrInflight[key] = cb ? [cb] : [];",
    "    var url = CODE_API + '?key=' + encodeURIComponent(key) + (force ? '&_=' + Date.now() : '');",
    "    fetch(url, { credentials: 'same-origin', cache: 'no-store' })",
    "      .then(function (r) { return r.json().then(function (j) { return { ok: r.ok, j: j }; }); })",
    "      .then(function (pack) {",
    "        var j = pack.j || {};",
    "        var art = j.article ? compactOem(j.article) : null;",
    "        if (art && isJunkOem(art)) art = null;",
    "        if (art) {",
    "          ocrCache[key] = art;",
    "          applyOcrToParts(key, art);",
    "        }",
    "        var list = ocrInflight[key] || [];",
    "        delete ocrInflight[key];",
    "        ocrDone = Math.min(ocrTotal, ocrDone + 1);",
    "        updateOcrBar();",
    "        for (var i = 0; i < list.length; i++) try { list[i](art); } catch (e) {}",
    "        renderPartsList();",
    "        pumpOcrQueue();",
    "      })",
    "      .catch(function (err) {",
    "        console.warn('[mont-ocr]', key.slice(0, 20), err);",
    "        var list = ocrInflight[key] || [];",
    "        delete ocrInflight[key];",
    "        ocrDone = Math.min(ocrTotal, ocrDone + 1);",
    "        updateOcrBar();",
    "        for (var i = 0; i < list.length; i++) try { list[i](null); } catch (e) {}",
    "        pumpOcrQueue();",
    "      });",
    "  }",
    "  function pumpOcrQueue() {",
    "    while (ocrActive < OCR_CONCURRENCY && ocrQueue.length) {",
    "      var k = ocrQueue.shift();",
    "      if (!k || ocrCache[k] || ocrInflight[k]) continue;",
    "      ocrActive++;",
    "      resolveCodeKey(k, function () { ocrActive = Math.max(0, ocrActive - 1); pumpOcrQueue(); });",
    "    }",
    "  }",
    "  function enqueueOcrKeys(keys) {",
    "    var uniq = [];",
    "    var seen = {};",
    "    for (var i = 0; i < keys.length; i++) {",
    "      var k = keys[i];",
    "      if (!k || seen[k] || ocrCache[k]) continue;",
    "      seen[k] = 1;",
    "      uniq.push(k);",
    "    }",
    "    ocrTotal = uniq.length + Object.keys(ocrCache).length;",
    "    ocrDone = Object.keys(ocrCache).length;",
    "    updateOcrBar();",
    "    for (var j = 0; j < uniq.length; j++) {",
    "      if (ocrQueue.indexOf(uniq[j]) < 0 && !ocrInflight[uniq[j]]) ocrQueue.push(uniq[j]);",
    "    }",
    "    pumpOcrQueue();",
    "  }",

    // ---- Parse legacy page ----
    "  function textClean(s) { return String(s || '').replace(/\\s+/g, ' ').trim(); }",
    "  function parseCrumbs() {",
    "    var out = [];",
    "    var nav = document.querySelector('.navigate-title, .BreadCrumbs');",
    "    if (!nav) return out;",
    "    var links = nav.querySelectorAll('a');",
    "    for (var i = 0; i < links.length; i++) {",
    "      var a = links[i];",
    "      var href = a.getAttribute('href') || '';",
    "      var label = textClean(a.textContent);",
    "      if (!label && href) label = '…';",
    "      if (label) out.push({ label: label, href: href });",
    "    }",
    "    var full = textClean(nav.textContent);",
    "    var parts = full.split(/>|»|\\\\/).map(textClean).filter(Boolean);",
    "    if (parts.length && (!out.length || out[out.length - 1].label !== parts[parts.length - 1])) {",
    "      var last = parts[parts.length - 1];",
    "      if (!out.some(function (c) { return c.label === last; })) out.push({ label: last, href: '' });",
    "    }",
    "    return out;",
    "  }",
    "  function parseNavItems() {",
    "    var items = [];",
    "    var seen = {};",
    "    function add(label, href, action, code, image) {",
    "      label = textClean(label);",
    "      if (!label || label.length < 1) return;",
    "      if (/^(\\.|…|\\/|>)$/i.test(label)) return;",
    "      if (/ВСЕ КАТАЛОГИ|АКСЕССУАРЫ|КАТАЛОГ ТО|exist\\.ru|liveinternet/i.test(label)) return;",
    "      var id = label + '|' + (href || '') + '|' + (action || '') + '|' + (image || '');",
    "      if (seen[id]) return;",
    "      seen[id] = 1;",
    "      var search = (code ? code + ' ' : '') + label;",
    "      items.push({",
    "        label: label,",
    "        href: href || '',",
    "        action: action || '',",
    "        code: code || '',",
    "        image: image || '',",
    "        search: search.toLowerCase()",
    "      });",
    "    }",
    "    document.querySelectorAll('.CNode').forEach(function (n) {",
    "      if (n.closest && (n.closest('#head') || n.closest('#footer') || n.closest('.navigate-title'))) return;",
    "      add(n.textContent, '', n.getAttribute('onclick') || '');",
    "    });",
    "    document.querySelectorAll('a[href]').forEach(function (a) {",
    "      if (a.closest && (a.closest('#head') || a.closest('#footer') || a.closest('.navigate-title') || a.closest('#mont-app'))) return;",
    "      var href = a.getAttribute('href') || '';",
    "      if (/Codes\\.ashx|exist\\.ru|liveinternet|pagead|javascript:void/i.test(href)) return;",
    "      // Groups / multi-scheme: javascript:submit(...)",
    "      if (/javascript:\\s*submit\\s*\\(/i.test(href)) {",
    "        var lab = textClean(a.textContent);",
    "        var code = '';",
    "        var imgEl = a.querySelector('img');",
    "        var imgSrc = '';",
    "        if (imgEl) {",
    "          imgSrc = imgEl.getAttribute('src') || imgEl.src || '';",
    "          try {",
    "            if (imgSrc && !/^https?:/i.test(imgSrc)) imgSrc = new URL(imgSrc, PAGE).toString();",
    "          } catch (e) {}",
    "        }",
    "        // Prefer visible label '[ 81-810 ] ОТДЕЛКА…' — never replace with '0' (4th Kia arg)",
    "        var codeM = lab.match(/\\[\\s*([0-9A-Z\\-]{2,12})\\s*\\]/i) || lab.match(/^([0-9]{2}(?:-[0-9]{3})?)\\b/);",
    "        if (codeM) code = codeM[1];",
    "        var args = parseSubmitArgs(href);",
    "        if (args && args.length >= 1) {",
    "          var a0 = String(args[0] || '');",
    "          var a1 = String(args[1] || '');",
    "          // Kia group: groupId '81-810', model GUID",
    "          if (/^\\d{2}-\\d{3}$/.test(a0)) {",
    "            if (!code) code = a0;",
    "            if (args[2] && String(args[2]).length > 3 && String(args[2]) !== '0' && String(args[2]).trim() !== '') {",
    "              if (!lab || lab.length < 4) lab = String(args[2]);",
    "            }",
    "          }",
    "          // Kia multi-scheme picker: submit(modelGuid, unitGuid, ' ')",
    "          if (isGuid(a0) && isGuid(a1)) {",
    "            if (!lab || lab.length < 2 || lab === '0') {",
    "              lab = 'Схема ' + (items.length + 1);",
    "            }",
    "          }",
    "        }",
    "        // empty label on scheme thumbs",
    "        if ((!lab || lab.length < 2) && imgSrc) lab = 'Схема ' + (items.length + 1);",
    "        if (!lab || lab.length < 2) return;",
    "        if (code && lab.indexOf(code) < 0) lab = code + ' · ' + lab;",
    "        add(lab, href, href, code, imgSrc);",
    "        return;",
    "      }",
    "      if (/\\.aspx/i.test(href) || /Group|Unit|SubGroup|Parts|Models/i.test(href)) {",
    "        var lab2 = textClean(a.textContent);",
    "        if (lab2 && lab2.length < 120 && lab2.length > 1) add(lab2, href, '');",
    "      }",
    "    });",
    "    document.querySelectorAll('[onclick*=\"submit\"]').forEach(function (el) {",
    "      if (el.closest && (el.closest('#head') || el.closest('#footer') || el.closest('.navigate-title'))) return;",
    "      var oc = el.getAttribute('onclick') || '';",
    "      var lab = textClean(el.textContent);",
    "      if (lab) add(lab, '', oc);",
    "    });",
    "    return items;",
    "  }",
    "  function parsePartRowsFromTable(table, callout, groupTitle) {",
    "    var rows = [];",
    "    if (!table) return rows;",
    "    // only direct body rows of this table — not nested .tbl replacement rows as separate parts",
    "    var trs = table.querySelectorAll(':scope > tbody > tr, :scope > tr');",
    "    if (!trs.length) trs = table.rows ? Array.prototype.slice.call(table.rows) : table.querySelectorAll('tr');",
    "    for (var i = 0; i < trs.length; i++) {",
    "      var tr = trs[i];",
    "      if (!tr || tr.querySelector('th')) continue;",
    "      // skip nested table rows that aren't direct children conceptually",
    "      if (tr.closest && tr.closest('table.tbl')) continue;",
    "      var imgs = tr.querySelectorAll(\"img[src*='Codes.ashx'], img[src*='codes.ashx']\");",
    "      // only Codes images that belong to this row's primary cell (not only nested? we need nested for replace)",
    "      if (!imgs.length) {",
    "        var tds0 = tr.querySelectorAll(':scope > td');",
    "        if (!tds0.length) tds0 = tr.querySelectorAll('td');",
    "        if (tds0.length >= 2) {",
    "          var maybe = looksLikeOem(tds0[0].textContent);",
    "          if (maybe) {",
    "            var name0 = textClean((tds0[1].querySelector('b') || tds0[1]).textContent);",
    "            if (!name0 || /^код\\s*детали/i.test(name0)) continue;",
    "            var desc0 = textClean(tds0[1].innerText || tds0[1].textContent).replace(name0, '').trim();",
    "            rows.push({",
    "              id: 't-' + callout + '-' + i + '-' + maybe,",
    "              callout: callout || '',",
    "              title: name0 || groupTitle || maybe,",
    "              desc: desc0,",
    "              qty: tds0[2] ? textClean(tds0[2].textContent).replace(/[^0-9]/g, '') : '',",
    "              info: '',",
    "              keys: [],",
    "              oems: [compactOem(maybe)],",
    "              replaceKeys: [],",
    "              replaceOems: [],",
    "              search: (callout + ' ' + name0 + ' ' + desc0 + ' ' + maybe).toLowerCase()",
    "            });",
    "          }",
    "        }",
    "        continue;",
    "      }",
    "      // primary code = first Codes img not inside nested .tbl; replaces = inside .tbl or subsequent",
    "      var mainKey = null;",
    "      var replaceKeys = [];",
    "      for (var j = 0; j < imgs.length; j++) {",
    "        var ik = extractCodeKey(imgs[j].getAttribute('src') || imgs[j].src || '');",
    "        if (!ik) continue;",
    "        var inTbl = imgs[j].closest && imgs[j].closest('table.tbl');",
    "        if (inTbl || (mainKey && j > 0)) replaceKeys.push(ik);",
    "        else if (!mainKey) mainKey = ik;",
    "        else replaceKeys.push(ik);",
    "      }",
    "      if (!mainKey && replaceKeys.length) { mainKey = replaceKeys.shift(); }",
    "      var tds = tr.children;",
    "      // prefer only top-level tds",
    "      var topTds = [];",
    "      for (var ti = 0; ti < tr.children.length; ti++) {",
    "        if ((tr.children[ti].tagName || '').toUpperCase() === 'TD') topTds.push(tr.children[ti]);",
    "      }",
    "      if (!topTds.length) topTds = tr.querySelectorAll('td');",
    "      var nameCell = topTds[1] || topTds[0];",
    "      var b = nameCell ? nameCell.querySelector('b') : null;",
    "      var title = b ? textClean(b.textContent) : (groupTitle || '');",
    "      if (!title || /^код\\s*детали/i.test(title) || /^доп\\.?\\s*опис/i.test(title)) {",
    "        title = groupTitle || title;",
    "      }",
    "      // build desc from name cell without nested tbl text",
    "      var desc = '';",
    "      if (nameCell) {",
    "        var clone = nameCell.cloneNode(true);",
    "        var nest = clone.querySelectorAll('table.tbl, table');",
    "        for (var ni = 0; ni < nest.length; ni++) {",
    "          if (nest[ni].classList && nest[ni].classList.contains('tbl')) nest[ni].parentNode.removeChild(nest[ni]);",
    "        }",
    "        desc = textClean(clone.innerText || clone.textContent);",
    "      }",
    "      if (title) desc = desc.replace(title, '').trim();",
    "      desc = desc.replace(/Код заменен на/gi, '').replace(/Цена\\s*\\*?/gi, '').replace(/^[-–—·\\s]+/, '').trim();",
    "      var qty = '';",
    "      var info = '';",
    "      if (topTds.length >= 3) qty = textClean(topTds[2].textContent).replace(/[^0-9]/g, '');",
    "      if (topTds.length >= 4) info = textClean(topTds[3].textContent);",
    "      var full = textClean(tr.innerText || tr.textContent);",
    "      var extra = [];",
    "      var mG = full.match(/Доп\\.\\s*информация:\\s*([^\\n]+)/i);",
    "      if (mG) extra.push(textClean(mG[1]));",
    "      var mC = full.match(/Комментарии:\\s*([^\\n]+)/i);",
    "      if (mC) extra.push(textClean(mC[1]));",
    "      if (extra.length) info = extra.join(' · ');",
    "      // skip junk",
    "      if (!mainKey && !title) continue;",
    "      rows.push({",
    "        id: 'p-' + (callout || 'x') + '-' + i + '-' + (mainKey || title).toString().slice(0, 24),",
    "        callout: callout || '',",
    "        title: title || groupTitle || 'Деталь',",
    "        desc: desc,",
    "        qty: qty,",
    "        info: info,",
    "        keys: mainKey ? [mainKey] : [],",
    "        oems: [],",
    "        replaceKeys: replaceKeys,",
    "        replaceOems: [],",
    "        search: (callout + ' ' + title + ' ' + desc + ' ' + info + ' ' + qty).toLowerCase()",
    "      });",
    "    }",
    "    return rows;",
    "  }",
    "  function parseParts() {",
    "    var parts = [];",
    "    var seenCallouts = {};",
    "    var plus = document.querySelectorAll('span.plus[key], .plus[key]');",
    "    if (plus.length) {",
    "      for (var i = 0; i < plus.length; i++) {",
    "        var sp = plus[i];",
    "        var callout = sp.getAttribute('key') || textClean((sp.querySelector('b') || {}).textContent || '');",
    "        if (!callout || seenCallouts[callout]) continue;",
    "        seenCallouts[callout] = 1;",
    "        var groupTitle = textClean(sp.textContent).replace(new RegExp('^' + callout + '\\\\s*'), '');",
    "        var box = document.getElementById(callout) || sp.nextElementSibling;",
    "        var table = null;",
    "        if (box) {",
    "          if (box.tagName === 'TABLE' && !(box.classList && box.classList.contains('tbl'))) table = box;",
    "          else table = box.querySelector('table:not(.tbl)');",
    "        }",
    "        if (table) parts = parts.concat(parsePartRowsFromTable(table, callout, groupTitle));",
    "      }",
    "    }",
    "    if (!parts.length) {",
    "      document.querySelectorAll('table').forEach(function (tb) {",
    "        if (!tb.querySelector(\"img[src*='Codes.ashx']\")) return;",
    "        if (tb.classList && tb.classList.contains('tbl')) return;",
    "        if (tb.closest && tb.closest('table.tbl')) return;",
    "        parts = parts.concat(parsePartRowsFromTable(tb, '', ''));",
    "      });",
    "    }",
    "    // Kia/Hyundai Unit: CNode list = short OEM codes (no Codes.ashx images)",
    "    if (!parts.length) {",
    "      var cnodes = document.querySelectorAll('.CNode[id], div.CNode[id]');",
    "      for (var ci = 0; ci < cnodes.length; ci++) {",
    "        var cn = cnodes[ci];",
    "        var cid = (cn.getAttribute('id') || '').trim();",
    "        if (!cid || seenCallouts[cid]) continue;",
    "        // skip pure layout nodes",
    "        if (/^(tree|root|main)$/i.test(cid)) continue;",
    "        seenCallouts[cid] = 1;",
    "        var ctxt = textClean(cn.textContent);",
    "        var ctitle = ctxt;",
    "        if (ctxt.indexOf(cid) === 0) ctitle = textClean(ctxt.slice(cid.length));",
    "        if (!ctitle) ctitle = cid;",
    "        parts.push({",
    "          id: 'cnode-' + cid,",
    "          callout: cid,",
    "          title: ctitle,",
    "          desc: '',",
    "          qty: '',",
    "          info: 'код детали (elcats)',",
    "          keys: [],",
    "          oems: [compactOem(cid)],",
    "          replaceKeys: [],",
    "          replaceOems: [],",
    "          search: (cid + ' ' + ctitle).toLowerCase()",
    "        });",
    "      }",
    "    }",
    "    var by = {};",
    "    var out = [];",
    "    for (var p = 0; p < parts.length; p++) {",
    "      var key = parts[p].id;",
    "      var contentKey = [parts[p].callout, parts[p].keys[0] || '', parts[p].oems && parts[p].oems[0] || '', parts[p].title, parts[p].desc, parts[p].qty].join('|');",
    "      if (by[key] || by[contentKey]) continue;",
    "      by[key] = 1;",
    "      by[contentKey] = 1;",
    "      out.push(parts[p]);",
    "    }",
    "    return out;",
    "  }",
    "  function collectHotspots(host) {",
    "    var hotspots = [];",
    "    if (!host) return hotspots;",
    "    var maps = host.querySelectorAll('.MapPoint, .MapPointNew');",
    "    for (var i = 0; i < maps.length; i++) {",
    "      var m = maps[i];",
    "      var st = m.getAttribute('style') || '';",
    "      var left = (st.match(/left:\\s*([\\d.]+)/i) || [])[1];",
    "      var top = (st.match(/top:\\s*([\\d.]+)/i) || [])[1];",
    "      var w = (st.match(/width:\\s*([\\d.]+)/i) || [])[1] || '20';",
    "      var h = (st.match(/height:\\s*([\\d.]+)/i) || [])[1] || '20';",
    "      var no = (m.getAttribute('no') || m.getAttribute('key') || textClean(m.textContent) || '').trim();",
    "      var none = String(m.getAttribute('none') || '').toLowerCase() === 'true';",
    "      var title = m.getAttribute('Title') || m.getAttribute('title') || '';",
    "      if (left == null || top == null) continue;",
    "      hotspots.push({ left: +left, top: +top, w: +w, h: +h, no: no, none: none, title: title });",
    "    }",
    "    return hotspots;",
    "  }",
    "  function parseSchemes() {",
    "    // IMPORTANT: do NOT match /CImages/op.gif — only real EPC diagrams (CImage.ashx)",
    "    var schemes = [];",
    "    var seen = {};",
    "    var imgs = document.querySelectorAll(",
    "      '#ctl00_cphMasterPage_imgParts, img[id*=\"imgParts\"], img[src*=\"CImage.ashx\"], img[src*=\"cimage.ashx\"]'",
    "    );",
    "    for (var i = 0; i < imgs.length; i++) {",
    "      var img = imgs[i];",
    "      var src = img.getAttribute('src') || img.src || '';",
    "      if (!src || seen[src]) continue;",
    "      if (/\\/CImages\\//i.test(src) || /op\\.gif|ajax-loader|info\\.png/i.test(src)) continue;",
    "      seen[src] = 1;",
    "      var host = img.closest('#ctl00_cphMasterPage_spnImage, [id*=\"spnImage\"]') || img.parentElement;",
    "      var hotspots = collectHotspots(host);",
    "      // also gather MapPoints in same table cell",
    "      var cell = img.closest('td');",
    "      if (cell && hotspots.length < 2) {",
    "        var more = collectHotspots(cell);",
    "        if (more.length > hotspots.length) hotspots = more;",
    "      }",
    "      schemes.push({",
    "        src: src,",
    "        width: img.naturalWidth || img.width || 0,",
    "        height: img.naturalHeight || img.height || 0,",
    "        hotspots: hotspots,",
    "        label: 'Схема ' + (schemes.length + 1)",
    "      });",
    "    }",
    "    return schemes;",
    "  }",
    "  function detectMode(parts, nav, schemes) {",
    "    if (parts.length > 0) return 'parts';",
    "    var hasHs = schemes.some(function (s) { return s.hotspots && s.hotspots.length > 0; });",
    "    // Unit/Parts with scheme but parts not yet parsed as Codes — still parts UI",
    "    if (hasHs && /Unit\\.aspx|Parts\\.aspx/i.test(PAGE)) return 'parts';",
    "    if (hasHs && nav.length === 0) return 'parts';",
    "    if (schemes.length && /Parts\\.aspx|Unit\\.aspx/i.test(PAGE)) return 'parts';",
    "    if (nav.length > 0) return 'nav';",
    "    if (/Group\\.aspx|SubGroup|Models\\.aspx|Default\\.aspx/i.test(PAGE)) return 'nav';",
    "    if (/Parts\\.aspx|Unit\\.aspx/i.test(PAGE)) return 'parts';",
    "    return 'other';",
    "  }",

    // ---- Render ----
    "  function matchQuery(text, q) {",
    "    if (!q) return true;",
    "    var t = String(text || '').toLowerCase();",
    "    var parts = q.toLowerCase().split(/\\s+/).filter(Boolean);",
    "    for (var i = 0; i < parts.length; i++) if (t.indexOf(parts[i]) < 0) return false;",
    "    return true;",
    "  }",
    "  function syncPartOems(p) {",
    "    if (p.keys && p.keys[0] && ocrCache[p.keys[0]]) p.oems = [ocrCache[p.keys[0]]];",
    "    if (p.replaceKeys && p.replaceKeys.length) {",
    "      p.replaceOems = p.replaceKeys.map(function (k) { return ocrCache[k]; }).filter(Boolean);",
    "    }",
    "  }",
    "  /** One card per callout; variants nested (no 60 identical pills). */",
    "  function groupedParts() {",
    "    var q = state.query;",
    "    var map = {};",
    "    var order = [];",
    "    for (var i = 0; i < state.parts.length; i++) {",
    "      var p = state.parts[i];",
    "      syncPartOems(p);",
    "      var bag = (p.search || '') + ' ' + (p.oems || []).join(' ') + ' ' + (p.replaceOems || []).join(' ');",
    "      if (!matchQuery(bag, q)) continue;",
    "      var ck = String(p.callout || '').trim();",
    "      var gk = ck || ('_t:' + (p.title || p.id));",
    "      if (!map[gk]) {",
    "        map[gk] = { callout: ck, title: p.title || 'Деталь', variants: [], search: '', vseen: {} };",
    "        order.push(gk);",
    "      }",
    "      var g = map[gk];",
    "      if (p.title && p.title.length > (g.title || '').length) g.title = p.title;",
    "      // dedupe identical variants",
    "      var vk = [p.keys && p.keys[0] || '', p.title || '', p.desc || '', p.qty || '', p.info || ''].join('|');",
    "      if (g.vseen[vk]) continue;",
    "      g.vseen[vk] = 1;",
    "      g.variants.push(p);",
    "      g.search += ' ' + bag;",
    "    }",
    "    // numeric callout sort (010 before 100)",
    "    order.sort(function (a, b) {",
    "      var na = parseInt(map[a].callout, 10);",
    "      var nb = parseInt(map[b].callout, 10);",
    "      var fa = isNaN(na); var fb = isNaN(nb);",
    "      if (!fa && !fb && na !== nb) return na - nb;",
    "      if (!fa && fb) return -1;",
    "      if (fa && !fb) return 1;",
    "      return String(map[a].callout).localeCompare(String(map[b].callout));",
    "    });",
    "    return order.map(function (k) { return map[k]; });",
    "  }",
    "  function filteredNav() {",
    "    return state.nav.filter(function (n) { return matchQuery(n.search, state.query); });",
    "  }",

    "  function renderCrumbs(el) {",
    "    if (!state.crumbs.length) { el.innerHTML = '<span class=\"mont-here\">Каталог OEM</span>'; return; }",
    "    var html = '';",
    "    for (var i = 0; i < state.crumbs.length; i++) {",
    "      var c = state.crumbs[i];",
    "      if (i) html += ' <span style=\"opacity:.45\">/</span> ';",
    "      if (c.href && i < state.crumbs.length - 1) {",
    "        html += '<a href=\"#\" data-href=\"' + String(c.href).replace(/\"/g, '&quot;') + '\">' + escapeHtml(c.label) + '</a>';",
    "      } else {",
    "        html += '<span class=\"mont-here\">' + escapeHtml(c.label) + '</span>';",
    "      }",
    "    }",
    "    el.innerHTML = html;",
    "  }",
    "  function escapeHtml(s) {",
    "    return String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\"/g, '&quot;');",
    "  }",

    "  function oemBtnHtml(oem, opts) {",
    "    opts = opts || {};",
    "    if (!oem) {",
    "      if (opts.failed) {",
    "        return '<button type=\"button\" class=\"mont-oem is-fail\" data-retry-key=\"' + escapeHtml(opts.key || '') + '\" data-name=\"' + escapeHtml(opts.name || '') + '\">OEM ? · ещё раз</button>';",
    "      }",
    "      return '<span class=\"mont-oem is-loading\" data-key=\"' + escapeHtml(opts.key || '') + '\">OEM…</span>';",
    "    }",
    "    var cls = 'mont-oem' + (opts.repl ? ' is-repl' : '');",
    "    return '<button type=\"button\" class=\"' + cls + '\" data-oem=\"' + escapeHtml(oem) + '\" data-name=\"' + escapeHtml(opts.name || '') + '\">' +",
    "      escapeHtml(formatOemDisplay(oem)) + '</button>';",
    "  }",

    "  function renderVariantOems(p) {",
    "    syncPartOems(p);",
    "    var html = '<div class=\"mont-oem-row\">';",
    "    if (p.oems && p.oems[0]) {",
    "      html += oemBtnHtml(p.oems[0], { name: p.title });",
    "    } else if (p.keys && p.keys[0]) {",
    "      var waiting = !!ocrInflight[p.keys[0]] || ocrQueue.indexOf(p.keys[0]) >= 0;",
    "      html += oemBtnHtml(null, { key: p.keys[0], name: p.title, failed: !waiting && ocrDone >= ocrTotal && ocrTotal > 0 });",
    "    }",
    "    if (p.replaceKeys && p.replaceKeys.length) {",
    "      html += '<span class=\"mont-oem-label\">→</span>';",
    "      if (p.replaceOems && p.replaceOems.length) {",
    "        for (var r = 0; r < p.replaceOems.length; r++) html += oemBtnHtml(p.replaceOems[r], { name: p.title, repl: true });",
    "      } else {",
    "        html += oemBtnHtml(null, { key: p.replaceKeys[0], name: p.title });",
    "      }",
    "    }",
    "    html += '<button type=\"button\" class=\"mont-oem is-md\" data-md-first=\"1\" data-id=\"' + escapeHtml(p.id) + '\">MD →</button>';",
    "    html += '</div>';",
    "    return html;",
    "  }",
    "  function cleanDesc(p) {",
    "    var d = textClean(p.desc || '');",
    "    // drop repeated title and noise",
    "    if (p.title) d = d.replace(p.title, '').trim();",
    "    d = d.replace(/^[-–—·\\s]+/, '').replace(/Цена\\s*\\*?/gi, '').trim();",
    "    return d;",
    "  }",
    "  function renderPartsList() {",
    "    var list = document.getElementById('mont-list');",
    "    var countEl = document.getElementById('mont-count');",
    "    if (!list) return;",
    "    var groups = groupedParts();",
    "    var varTotal = 0;",
    "    for (var g0 = 0; g0 < groups.length; g0++) varTotal += groups[g0].variants.length;",
    "    if (countEl) countEl.textContent = groups.length + (varTotal !== groups.length ? ' (' + varTotal + ')' : '');",
    "    if (!groups.length) {",
    "      list.innerHTML = '<div class=\"mont-empty\">Ничего не найдено. Измените запрос поиска.</div>';",
    "      return;",
    "    }",
    "    var html = '';",
    "    for (var i = 0; i < groups.length; i++) {",
    "      var g = groups[i];",
    "      var active = state.activeCallout && String(g.callout) === String(state.activeCallout);",
    "      var multi = g.variants.length > 1;",
    "      html += '<article class=\"mont-card' + (active ? ' is-active' : '') + (multi ? ' has-vars' : '') + '\" data-callout=\"' + escapeHtml(g.callout) + '\">';",
    "      html += '<div class=\"mont-card-head\" data-callout-click=\"' + escapeHtml(g.callout) + '\">';",
    "      if (g.callout) html += '<span class=\"mont-callout\">' + escapeHtml(g.callout) + '</span>';",
    "      html += '<div class=\"mont-card-title\">' + escapeHtml(g.title) + '</div>';",
    "      if (multi) html += '<span class=\"mont-card-count\">' + g.variants.length + ' вар.</span>';",
    "      html += '</div>';",
    "      html += '<div class=\"mont-variants\">';",
    "      for (var v = 0; v < g.variants.length; v++) {",
    "        var p = g.variants[v];",
    "        var desc = cleanDesc(p);",
    "        html += '<div class=\"mont-var\" data-id=\"' + escapeHtml(p.id) + '\">';",
    "        if (desc || p.qty || p.info) {",
    "          html += '<div class=\"mont-card-meta\">';",
    "          if (p.qty) html += '<span class=\"mont-chip qty\">×' + escapeHtml(p.qty) + '</span>';",
    "          if (p.info) html += '<span class=\"mont-chip\">' + escapeHtml(p.info) + '</span>';",
    "          html += '</div>';",
    "          if (desc) html += '<div class=\"mont-var-desc\">' + escapeHtml(desc) + '</div>';",
    "        } else if (multi && p.title && p.title !== g.title) {",
    "          html += '<div class=\"mont-var-desc\"><b>' + escapeHtml(p.title) + '</b></div>';",
    "        }",
    "        html += renderVariantOems(p);",
    "        html += '</div>';",
    "      }",
    "      html += '</div></article>';",
    "    }",
    "    list.innerHTML = html;",
    "  }",

    "  function renderNavList() {",
    "    var list = document.getElementById('mont-nav');",
    "    var countEl = document.getElementById('mont-count');",
    "    var hintEl = document.getElementById('mont-scheme-hint');",
    "    if (!list) return;",
    "    var items = filteredNav();",
    "    if (countEl) countEl.textContent = items.length + ' / ' + state.nav.length;",
    "    if (!items.length) {",
    "      list.innerHTML = '<div class=\"mont-empty\">Узлы не найдены по запросу.</div>';",
    "      if (hintEl) hintEl.style.display = 'none';",
    "      return;",
    "    }",
    "    var schemeCount = 0;",
    "    for (var si = 0; si < items.length; si++) if (items[si].image) schemeCount++;",
    "    var isSchemePicker = schemeCount >= 2 || (schemeCount >= 1 && /Unit\\.aspx/i.test(PAGE));",
    "    list.className = 'mont-nav-grid' + (isSchemePicker ? ' is-schemes' : '');",
    "    if (hintEl) {",
    "      if (isSchemePicker) {",
    "        hintEl.style.display = 'block';",
    "        hintEl.innerHTML = '<strong>Выберите схему</strong> — для этого узла несколько вариантов комплектации. Нажмите на картинку.';",
    "      } else {",
    "        hintEl.style.display = 'none';",
    "      }",
    "    }",
    "    var html = '';",
    "    for (var i = 0; i < items.length; i++) {",
    "      var n = items[i];",
    "      var cls = 'mont-nav-item' + (n.image ? ' is-scheme' : '');",
    "      html += '<button type=\"button\" class=\"' + cls + '\" data-i=\"' + i + '\" data-href=\"' + escapeHtml(n.href) + '\" data-action=\"' + escapeHtml(n.action) + '\">';",
    "      if (n.image) {",
    "        html += '<img class=\"mont-scheme-thumb\" src=\"' + escapeHtml(n.image) + '\" alt=\"' + escapeHtml(n.label) + '\" loading=\"lazy\" />';",
    "        html += '<span class=\"mont-nav-label\">' + escapeHtml(n.label) + '</span>';",
    "      } else {",
    "        html += '<span class=\"arrow\">›</span><span class=\"mont-nav-label\">' + escapeHtml(n.label) + '</span>';",
    "      }",
    "      html += '</button>';",
    "    }",
    "    list.innerHTML = html;",
    "  }",

    "  function applySchemeZoom() {",
    "    var stage = document.getElementById('mont-scheme-stage');",
    "    if (stage) stage.style.transform = 'scale(' + schemeZoom + ')';",
    "    var z = document.getElementById('mont-zoom-label');",
    "    if (z) z.textContent = Math.round(schemeZoom * 100) + '%';",
    "  }",

    "  function highlightCallout(no) {",
    "    state.activeCallout = String(no || '');",
    "    var spots = document.querySelectorAll('.mont-hotspot');",
    "    for (var i = 0; i < spots.length; i++) {",
    "      spots[i].classList.toggle('is-active', spots[i].getAttribute('data-no') === state.activeCallout);",
    "    }",
    "    renderPartsList();",
    "    var card = null;",
    "    var cards = document.querySelectorAll('.mont-card[data-callout]');",
    "    for (var ci = 0; ci < cards.length; ci++) {",
    "      if (cards[ci].getAttribute('data-callout') === state.activeCallout) { card = cards[ci]; break; }",
    "    }",
    "    if (card) {",
    "      var list = document.getElementById('mont-list');",
    "      if (list) {",
    "        var top = card.offsetTop - list.offsetTop - 8;",
    "        list.scrollTo({ top: Math.max(0, top), behavior: 'smooth' });",
    "      } else card.scrollIntoView({ behavior: 'smooth', block: 'nearest' });",
    "    }",
    "    // bring hotspot into scheme view",
    "    var active = document.querySelector('.mont-hotspot.is-active');",
    "    var view = document.getElementById('mont-scheme-view');",
    "    if (active && view) {",
    "      try {",
    "        var ar = active.getBoundingClientRect();",
    "        var vr = view.getBoundingClientRect();",
    "        if (ar.top < vr.top || ar.bottom > vr.bottom || ar.left < vr.left || ar.right > vr.right) {",
    "          active.scrollIntoView({ block: 'center', inline: 'center', behavior: 'smooth' });",
    "        }",
    "      } catch (e) {}",
    "    }",
    "  }",

    "  function parseSubmitArgs(raw) {",
    "    var m = String(raw || '').match(/submit\\s*\\((\\s*[\\s\\S]*?)\\)\\s*;?\\s*$/i)",
    "      || String(raw || '').match(/submit\\s*\\(([\\s\\S]*)\\)/i);",
    "    if (!m) return null;",
    "    var args = m[1];",
    "    var parts = [];",
    "    // '...' | \"...\" | null | undefined | bare number/id",
    "    var re = /'((?:\\\\'|[^'])*)'|\"((?:\\\\\"|[^\"])*)\"|\\bnull\\b|\\bundefined\\b|([A-Za-z0-9_.\\-]+)/gi;",
    "    var mm;",
    "    while ((mm = re.exec(args))) {",
    "      if (mm[1] != null) parts.push(mm[1].replace(/\\\\'/g, \"'\"));",
    "      else if (mm[2] != null) parts.push(mm[2].replace(/\\\\\"/g, '\"'));",
    "      else if (/^null$/i.test(mm[0])) parts.push(null);",
    "      else if (/^undefined$/i.test(mm[0])) parts.push(undefined);",
    "      else if (mm[3] != null) parts.push(mm[3]);",
    "    }",
    "    return parts;",
    "  }",
    "  function isGuid(s) { return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(String(s || '')); }",
    "  function navigateFromSubmitArgs(parts, label) {",
    "    if (!parts || parts.length < 2) return false;",
    "    var model = parts[0];",
    "    var groupOrUnit = parts[1];",
    "    var title = '';",
    "    var targetName = 'SubGroup.aspx';",
    "    var useGroupId = false;",
    "    var useUnit = false;",
    "    // Kia multi-scheme: submit(modelGuid, unitGuid, title) → Parts.aspx",
    "    if (isGuid(parts[0]) && isGuid(parts[1])) {",
    "      model = parts[0];",
    "      groupOrUnit = parts[1];",
    "      title = parts[2] != null ? String(parts[2]) : (label || '');",
    "      if (!title || !String(title).trim() || title === '0') title = label || ' ';",
    "      targetName = 'Parts.aspx';",
    "      useUnit = true;",
    "    } else if (isGuid(parts[1]) && !isGuid(parts[0])) {",
    "      // Kia/Hyundai Group: submit(groupId, model, title, value) → Unit.aspx",
    "      groupOrUnit = parts[0];",
    "      model = parts[1];",
    "      title = parts[2] != null ? String(parts[2]) : (label || '');",
    "      targetName = 'Unit.aspx';",
    "      useGroupId = true;",
    "    } else {",
    "      // Mercedes Group: submit(model, groupId, value, title) → SubGroup.aspx",
    "      // SubGroup: submit(model, unit, title) → Parts.aspx",
    "      if (parts.length >= 4) title = parts[3] != null && String(parts[3]) !== '0' && String(parts[3]) !== 'null' ? String(parts[3]) : (parts[2] != null ? String(parts[2]) : '');",
    "      else if (parts.length >= 3 && parts[2] != null && parts[2] !== '') title = String(parts[2]);",
    "      if (!title || title === '0' || title === 'null') title = label || '';",
    "      if (/Group\\.aspx/i.test(PAGE) && !/SubGroup/i.test(PAGE)) targetName = 'SubGroup.aspx';",
    "      else if (/SubGroup\\.aspx/i.test(PAGE)) { targetName = 'Parts.aspx'; useUnit = true; }",
    "      else if (/Unit\\.aspx/i.test(PAGE)) { targetName = 'Parts.aspx'; useUnit = true; }",
    "      else if (/Parts\\.aspx/i.test(PAGE)) { targetName = 'Parts.aspx'; useUnit = true; }",
    "      else if (/Models\\.aspx|Default\\.aspx/i.test(PAGE)) targetName = 'Group.aspx';",
    "    }",
    "    if (!title || title === '0') title = label || ' ';",
    "    try {",
    "      var u = new URL(targetName, PAGEDIR);",
    "      if (model) u.searchParams.set('Model', String(model));",
    "      if (groupOrUnit != null && groupOrUnit !== '') {",
    "        if (useGroupId) u.searchParams.set('GroupId', String(groupOrUnit));",
    "        else if (useUnit) u.searchParams.set('Unit', String(groupOrUnit));",
    "        else if (/SubGroup\\.aspx|Group\\.aspx/i.test(targetName)) u.searchParams.set('Group', String(groupOrUnit));",
    "        else u.searchParams.set('Unit', String(groupOrUnit));",
    "      }",
    "      if (title && String(title).trim()) u.searchParams.set('Title', String(title).trim());",
    "      goElcats(u.toString());",
    "      return true;",
    "    } catch (e) { return false; }",
    "  }",
    "  function runNavAction(href, action, label) {",
    "    var raw = action || href || '';",
    "    if (href && /javascript:\\s*submit/i.test(href)) raw = href;",
    "    // Prefer safe arg parse — never Function() with Cyrillic titles (breaks on quotes)",
    "    if (/submit\\s*\\(/i.test(raw)) {",
    "      var parts = parseSubmitArgs(raw);",
    "      var fn = null;",
    "      try { fn = window.submit || (typeof submit === 'function' ? submit : null); } catch (e) {}",
    "      // Prefer our URL navigation (avoids form &amp; bugs + relative Parts.aspx)",
    "      if (navigateFromSubmitArgs(parts, label)) return;",
    "      if (fn && parts && parts.length) {",
    "        try {",
    "          fn.apply(window, parts);",
    "          return;",
    "        } catch (e) { console.warn('[mont-nav] submit.apply failed', e); }",
    "      }",
    "    }",
    "    if (href && href.charAt(0) !== '#' && href.indexOf('javascript:') !== 0) {",
    "      goElcats(href);",
    "      return;",
    "    }",
    "    // click original anchor in hidden source",
    "    var nodes = document.querySelectorAll('#mont-source a[href*=\"javascript:submit\"], #mont-source .CNode, #mont-source a');",
    "    var want = textClean(label || '').replace(/^\\d+\\s*·\\s*/, '');",
    "    for (var i = 0; i < nodes.length; i++) {",
    "      var t = textClean(nodes[i].textContent);",
    "      var href2 = nodes[i].getAttribute('href') || '';",
    "      if (want && (t === want || t.indexOf(want) >= 0 || want.indexOf(t) >= 0)) {",
    "        if (/javascript:\\s*submit/i.test(href2)) {",
    "          var p2 = parseSubmitArgs(href2);",
    "          if (navigateFromSubmitArgs(p2, label)) return;",
    "        }",
    "        try { nodes[i].click(); return; } catch (e) {}",
    "      }",
    "    }",
    "    toast('Не удалось открыть узел');",
    "  }",

    "  function renderSchemeStage() {",
    "    var view = document.getElementById('mont-scheme-view');",
    "    if (!view) return;",
    "    var schemes = state.schemes || [];",
    "    var scheme = schemes[state.schemeIdx] || schemes[0];",
    "    if (!scheme || !scheme.src) {",
    "      view.innerHTML = '<div class=\"mont-empty\">Схема недоступна</div>';",
    "      return;",
    "    }",
    "    var html = '<div class=\"mont-scheme-stage\" id=\"mont-scheme-stage\">';",
    "    html += '<img class=\"mont-scheme-img\" id=\"mont-scheme-img\" alt=\"scheme\" src=\"' + escapeHtml(scheme.src) + '\" />';",
    "    var hsList = scheme.hotspots || [];",
    "    for (var h = 0; h < hsList.length; h++) {",
    "      var hs = hsList[h];",
    "      var cls = 'mont-hotspot' + (hs.none ? ' is-off' : '');",
    "      if (state.activeCallout && String(hs.no) === String(state.activeCallout)) cls += ' is-active';",
    "      html += '<div class=\"' + cls + '\" data-no=\"' + escapeHtml(hs.no) + '\" title=\"' + escapeHtml(hs.title || hs.no) + '\" style=\"left:' + hs.left + 'px;top:' + hs.top + 'px;width:' + hs.w + 'px;height:' + hs.h + 'px\">' + escapeHtml(hs.no) + '</div>';",
    "    }",
    "    html += '</div>';",
    "    view.innerHTML = html;",
    "    var img = document.getElementById('mont-scheme-img');",
    "    if (img) {",
    "      img.onload = function () {",
    "        try {",
    "          var vw = view.clientWidth - 16;",
    "          if (img.naturalWidth > vw && vw > 0) {",
    "            schemeZoom = Math.min(1, Math.max(0.35, vw / img.naturalWidth));",
    "            applySchemeZoom();",
    "          }",
    "        } catch (e) {}",
    "      };",
    "    }",
    "    applySchemeZoom();",
    "  }",

    "  function mountApp() {",
    "    var content = document.getElementById('content') || document.body;",
    "    if (!document.getElementById('mont-source')) {",
    "      var src = document.createElement('div');",
    "      src.id = 'mont-source';",
    "      while (content.firstChild) src.appendChild(content.firstChild);",
    "      document.body.appendChild(src);",
    "    }",
    "    var app = document.getElementById('mont-app');",
    "    if (!app) {",
    "      app = document.createElement('div');",
    "      app.id = 'mont-app';",
    "      content.appendChild(app);",
    "    }",

    "    var searchPh = state.mode === 'parts'",
    "      ? 'Поиск по деталям, OEM, выноске, G-кодам…'",
    "      : 'Поиск по группам и узлам (например: подвеска, 24, тормоз)…';",

    "    var bodyHtml = '';",
    "    if (state.mode === 'parts') {",
    "      bodyHtml += '<div class=\"mont-body\">';",
    "      bodyHtml += '<div class=\"mont-scheme-col\">';",
    "      bodyHtml += '<div class=\"mont-scheme-toolbar\"><span>Схема</span>';",
    "      bodyHtml += '<button type=\"button\" class=\"mont-icon-btn\" id=\"mont-z-out\" title=\"Мельче\">−</button>';",
    "      bodyHtml += '<span class=\"mont-meta\" id=\"mont-zoom-label\">100%</span>';",
    "      bodyHtml += '<button type=\"button\" class=\"mont-icon-btn\" id=\"mont-z-in\" title=\"Крупнее\">+</button>';",
    "      bodyHtml += '<button type=\"button\" class=\"mont-icon-btn\" id=\"mont-z-fit\" title=\"Вписать\">Fit</button>';",
    "      bodyHtml += '</div>';",
    "      if (state.schemes.length > 1) {",
    "        bodyHtml += '<div class=\"mont-scheme-tabs\" id=\"mont-scheme-tabs\">';",
    "        for (var si = 0; si < state.schemes.length; si++) {",
    "          bodyHtml += '<button type=\"button\" class=\"mont-scheme-tab' + (si === state.schemeIdx ? ' is-on' : '') + '\" data-si=\"' + si + '\">' + escapeHtml(state.schemes[si].label || ('Схема ' + (si + 1))) + '</button>';",
    "        }",
    "        bodyHtml += '</div>';",
    "      }",
    "      bodyHtml += '<div class=\"mont-scheme-view\" id=\"mont-scheme-view\"></div></div>';",
    "      bodyHtml += '<div class=\"mont-list-col\">';",
    "      bodyHtml += '<div class=\"mont-list-head\"><h2>Детали</h2><span class=\"mont-badge\" id=\"mont-count\">0</span>';",
    "      bodyHtml += '<span class=\"mont-ocr-bar\" id=\"mont-ocr-bar\"></span></div>';",
    "      bodyHtml += '<div class=\"mont-list\" id=\"mont-list\"></div>';",
    "      bodyHtml += '</div></div>';",
    "    } else if (state.mode === 'nav') {",
    "      bodyHtml += '<div class=\"mont-list-head\" style=\"border-bottom:1px solid var(--m-border)\"><h2 id=\"mont-nav-title\">Группы / узлы</h2><span class=\"mont-badge\" id=\"mont-count\">0</span></div>';",
    "      bodyHtml += '<div class=\"mont-scheme-hint\" id=\"mont-scheme-hint\" style=\"display:none\"></div>';",
    "      bodyHtml += '<div class=\"mont-nav-grid\" id=\"mont-nav\"></div>';",
    "    } else {",
    "      bodyHtml += '<div class=\"mont-empty\">Нет распознанных узлов на этой странице. Попробуйте шаг назад в крошках.</div>';",
    "      bodyHtml += '<div class=\"mont-scheme-hint\" id=\"mont-scheme-hint\" style=\"display:none\"></div>';",
    "      bodyHtml += '<div class=\"mont-nav-grid\" id=\"mont-nav\"></div>';",
    "    }",

    "    app.innerHTML =",
    "      '<div class=\"mont-top\">' +",
    "        '<div class=\"mont-crumbs\" id=\"mont-crumbs\"></div>' +",
    "        '<div class=\"mont-top-row\">' +",
    "          '<div class=\"mont-search-wrap\">' +",
    "            '<span class=\"mont-search-ico\">⌕</span>' +",
    "            '<input class=\"mont-search\" id=\"mont-search\" type=\"search\" placeholder=\"' + escapeHtml(searchPh) + '\" autocomplete=\"off\" />' +",
    "          '</div>' +",
    "          '<span class=\"mont-meta\" id=\"mont-hint\">Клик OEM → MD</span>' +",
    "        '</div>' +",
    "      '</div>' + bodyHtml;",

    "    renderCrumbs(document.getElementById('mont-crumbs'));",
    "    if (state.mode === 'parts') {",
    "      renderSchemeStage();",
    "      renderPartsList();",
    "      updateOcrBar();",
    "    }",
    "    if (state.mode === 'nav' || state.mode === 'other') renderNavList();",

    "    var search = document.getElementById('mont-search');",
    "    if (search) {",
    "      search.value = state.query;",
    "      search.addEventListener('input', function () {",
    "        state.query = search.value || '';",
    "        if (state.mode === 'parts') renderPartsList();",
    "        else renderNavList();",
    "      });",
    "    }",

    "    var view = document.getElementById('mont-scheme-view');",
    "    var zin = document.getElementById('mont-z-in');",
    "    var zout = document.getElementById('mont-z-out');",
    "    var zfit = document.getElementById('mont-z-fit');",
    "    if (zin) zin.onclick = function () { schemeZoom = Math.min(3, schemeZoom + 0.15); applySchemeZoom(); };",
    "    if (zout) zout.onclick = function () { schemeZoom = Math.max(0.25, schemeZoom - 0.15); applySchemeZoom(); };",
    "    if (zfit && view) zfit.onclick = function () {",
    "      var img = document.getElementById('mont-scheme-img');",
    "      if (!img) return;",
    "      var vw = view.clientWidth - 16;",
    "      var vh = view.clientHeight - 16;",
    "      if (img.naturalWidth && vw > 0) {",
    "        schemeZoom = Math.min(vw / img.naturalWidth, vh / (img.naturalHeight || 1), 1);",
    "        if (schemeZoom < 0.25) schemeZoom = 0.25;",
    "        applySchemeZoom();",
    "      }",
    "    };",
    "    if (view) {",
    "      var pan = { on: false, x: 0, y: 0, sl: 0, st: 0 };",
    "      view.addEventListener('mousedown', function (e) {",
    "        if (e.target.closest && e.target.closest('.mont-hotspot')) return;",
    "        pan.on = true; pan.x = e.clientX; pan.y = e.clientY; pan.sl = view.scrollLeft; pan.st = view.scrollTop;",
    "        view.classList.add('is-panning');",
    "      });",
    "      window.addEventListener('mouseup', function () { pan.on = false; view.classList.remove('is-panning'); });",
    "      window.addEventListener('mousemove', function (e) {",
    "        if (!pan.on) return;",
    "        view.scrollLeft = pan.sl - (e.clientX - pan.x);",
    "        view.scrollTop = pan.st - (e.clientY - pan.y);",
    "      });",
    "    }",

    "    app.addEventListener('click', function (ev) {",
    "      var t = ev.target;",
    "      if (!t || !t.closest) return;",
    "      var tab = t.closest('.mont-scheme-tab');",
    "      if (tab) {",
    "        state.schemeIdx = +tab.getAttribute('data-si') || 0;",
    "        var tabs = document.querySelectorAll('.mont-scheme-tab');",
    "        for (var ti = 0; ti < tabs.length; ti++) tabs[ti].classList.toggle('is-on', ti === state.schemeIdx);",
    "        renderSchemeStage();",
    "        return;",
    "      }",
    "      var crumb = t.closest('#mont-crumbs a[data-href]');",
    "      if (crumb) {",
    "        ev.preventDefault();",
    "        goElcats(crumb.getAttribute('data-href'));",
    "        return;",
    "      }",
    "      var retry = t.closest('[data-retry-key]');",
    "      if (retry) {",
    "        ev.preventDefault();",
    "        ev.stopPropagation();",
    "        var rk = retry.getAttribute('data-retry-key');",
    "        toast('Повторно читаем OEM…');",
    "        resolveCodeKey(rk, function (a) {",
    "          if (a) { toast('OEM ' + formatOemDisplay(a)); renderPartsList(); }",
    "          else toast('Не удалось прочитать OEM');",
    "        }, true);",
    "        return;",
    "      }",
    "      var oem = t.closest('.mont-oem[data-oem]');",
    "      if (oem && !oem.getAttribute('data-md-first')) {",
    "        ev.preventDefault();",
    "        ev.stopPropagation();",
    "        postOem(oem.getAttribute('data-oem'), oem.getAttribute('data-name') || '');",
    "        return;",
    "      }",
    "      var mdFirst = t.closest('[data-md-first]');",
    "      if (mdFirst) {",
    "        ev.preventDefault();",
    "        ev.stopPropagation();",
    "        var pid = mdFirst.getAttribute('data-id') || '';",
    "        var part = null;",
    "        for (var pi = 0; pi < state.parts.length; pi++) if (state.parts[pi].id === pid) { part = state.parts[pi]; break; }",
    "        if (!part) { toast('Нет данных'); return; }",
    "        var art = (part.oems && part.oems[0]) || (part.replaceOems && part.replaceOems[0]) || '';",
    "        if (!art && part.keys && part.keys[0] && ocrCache[part.keys[0]]) art = ocrCache[part.keys[0]];",
    "        if (art) { postOem(art, part.title); return; }",
    "        if (part.keys && part.keys[0]) {",
    "          toast('Читаем OEM…');",
    "          resolveCodeKey(part.keys[0], function (a) {",
    "            if (a) postOem(a, part.title);",
    "            else toast('Не удалось прочитать OEM — нажмите «ещё раз»');",
    "          }, true);",
    "          return;",
    "        }",
    "        toast('В строке нет OEM-кода');",
    "        return;",
    "      }",
    "      var head = t.closest('[data-callout-click], .mont-card-head');",
    "      if (head) {",
    "        var co = head.getAttribute('data-callout-click') || (head.closest('.mont-card') && head.closest('.mont-card').getAttribute('data-callout')) || '';",
    "        if (co) highlightCallout(co);",
    "        return;",
    "      }",
    "      var spot = t.closest('.mont-hotspot');",
    "      if (spot) {",
    "        ev.preventDefault();",
    "        highlightCallout(spot.getAttribute('data-no') || '');",
    "        return;",
    "      }",
    "      var nav = t.closest('.mont-nav-item');",
    "      if (nav) {",
    "        ev.preventDefault();",
    "        var nidx = +nav.getAttribute('data-i');",
    "        var item = filteredNav()[nidx];",
    "        if (item) runNavAction(item.href, item.action, item.label);",
    "        else runNavAction(nav.getAttribute('data-href'), nav.getAttribute('data-action'), nav.textContent);",
    "      }",
    "    });",
    "  }",

    "  function boot() {",
    "    applyTheme();",
    "    stripBases();",
    "    try {",
    "      state.crumbs = parseCrumbs();",
    "      state.parts = parseParts();",
    "      state.nav = parseNavItems();",
    "      state.schemes = parseSchemes();",
    "      state.schemeIdx = 0;",
    "      // Multi-scheme picker (Kia hatch etc.): nav items with thumbnails — not parts list",
    "      var schemeNav = 0;",
    "      for (var ni = 0; ni < state.nav.length; ni++) if (state.nav[ni].image) schemeNav++;",
    "      var isMultiScheme = schemeNav >= 2 || (schemeNav >= 1 && /Unit\\.aspx/i.test(PAGE) && state.nav.length <= 6);",
    "      if (isMultiScheme) {",
    "        state.parts = [];",
    "        state.schemes = [];",
    "        state.mode = 'nav';",
    "      } else {",
    "        if (state.parts.length) state.nav = [];",
    "        state.mode = detectMode(state.parts, state.nav, state.schemes);",
    "        if (state.mode === 'parts' && !state.parts.length && state.nav.length) {",
    "          state.mode = 'nav';",
    "          state.schemes = [];",
    "        }",
    "        if (state.mode === 'nav') state.schemes = [];",
    "      }",
    "      mountApp();",
    "      if (isMultiScheme) {",
    "        var nt = document.getElementById('mont-nav-title');",
    "        if (nt) nt.textContent = 'Выбор схемы';",
    "      }",
    "      var keys = [];",
    "      for (var i = 0; i < state.parts.length; i++) {",
    "        var p = state.parts[i];",
    "        if (p.keys) keys = keys.concat(p.keys);",
    "        if (p.replaceKeys) keys = keys.concat(p.replaceKeys);",
    "      }",
    "      if (keys.length) enqueueOcrKeys(keys);",
    "    } catch (e) {",
    "      console.error('[mont-elcats-ui]', e);",
    "      toast('UI error');",
    "    }",
    "  }",

    // ---- form / link intercepts on original source still needed for submit() ----
    "  document.addEventListener('submit', function (ev) {",
    "    var form = ev.target;",
    "    if (!form || form.tagName !== 'FORM') return;",
    "    var method = String(form.getAttribute('method') || form.method || 'get').toLowerCase();",
    "    if (method !== 'post') {",
    "      ev.preventDefault();",
    "      if (ev.stopImmediatePropagation) ev.stopImmediatePropagation();",
    "      navigateFormGet(form, ev.submitter || null);",
    "      return false;",
    "    }",
    "    var postTarget = absElcats(resolveFormActionRaw(form));",
    "    form.setAttribute('action', toProxy(postTarget));",
    "    try { form.action = form.getAttribute('action'); } catch (e) {}",
    "  }, true);",

    "  try {",
    "    var forms = document.getElementsByTagName('form');",
    "    for (var fi = 0; fi < forms.length; fi++) {",
    "      var fa = forms[fi].getAttribute('action');",
    "      if (fa && !forms[fi].getAttribute('data-mont-action')) forms[fi].setAttribute('data-mont-action', fa);",
    "      forceFormProxy(forms[fi]);",
    "    }",
    "  } catch (e) {}",

    "  try {",
    "    var desc = Object.getOwnPropertyDescriptor(HTMLFormElement.prototype, 'action');",
    "    if (desc && desc.set) {",
    "      Object.defineProperty(HTMLFormElement.prototype, 'action', {",
    "        configurable: true, enumerable: true,",
    "        get: function () { return desc.get.call(this); },",
    "        set: function (v) {",
    "          try {",
    "            this.setAttribute('data-mont-action', String(v || ''));",
    "            return desc.set.call(this, toProxy(v || PAGE));",
    "          } catch (e) { return desc.set.call(this, v); }",
    "        }",
    "      });",
    "    }",
    "  } catch (e) {}",

    "  try {",
    "    var nativeSubmit = HTMLFormElement.prototype.submit;",
    "    HTMLFormElement.prototype.submit = function () {",
    "      var method = String(this.getAttribute('method') || this.method || 'get').toLowerCase();",
    "      if (method !== 'post') { navigateFormGet(this, null); return; }",
    "      var postTarget = absElcats(resolveFormActionRaw(this));",
    "      var proxied = toProxy(postTarget);",
    "      this.setAttribute('action', proxied);",
    "      try { this.action = proxied; } catch (e) {}",
    "      return nativeSubmit.call(this);",
    "    };",
    "  } catch (e) {}",

    "  // Patch legacy submit() used by elcats to go through proxy after it sets form.action",
    "  // (action setter already proxies)",

    "  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot);",
    "  else boot();",
    "  window.addEventListener('load', function () { applyTheme(); });",
    "})();",
    "</script>",
  ];
  return lines.join("\n");
}
